spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance?serverTimezone=UTC&useSSL=false #jdbc:[Database]://localhost:3306/[Database???]
    username: "root" #[DB ???]
    password: "0721" #[DB ????]
    driver-class-name: com.mysql.cj.jdbc.Driver #[JDBC ????]